/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GitMonitorRouteImport } from './routes/git-monitor'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionNewRouteImport } from './routes/session/new'
import { Route as SessionSessionIdRouteImport } from './routes/session/$sessionId'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GitMonitorRoute = GitMonitorRouteImport.update({
  id: '/git-monitor',
  path: '/git-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionNewRoute = SessionNewRouteImport.update({
  id: '/session/new',
  path: '/session/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/git-monitor': typeof GitMonitorRoute
  '/history': typeof HistoryRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/new': typeof SessionNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/git-monitor': typeof GitMonitorRoute
  '/history': typeof HistoryRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/new': typeof SessionNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/git-monitor': typeof GitMonitorRoute
  '/history': typeof HistoryRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/session/new': typeof SessionNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/git-monitor'
    | '/history'
    | '/session/$sessionId'
    | '/session/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/git-monitor'
    | '/history'
    | '/session/$sessionId'
    | '/session/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/git-monitor'
    | '/history'
    | '/session/$sessionId'
    | '/session/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  GitMonitorRoute: typeof GitMonitorRoute
  HistoryRoute: typeof HistoryRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  SessionNewRoute: typeof SessionNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-monitor': {
      id: '/git-monitor'
      path: '/git-monitor'
      fullPath: '/git-monitor'
      preLoaderRoute: typeof GitMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/new': {
      id: '/session/new'
      path: '/session/new'
      fullPath: '/session/new'
      preLoaderRoute: typeof SessionNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  GitMonitorRoute: GitMonitorRoute,
  HistoryRoute: HistoryRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  SessionNewRoute: SessionNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
