"""sessions 테이블에 worktree_name 추가

Revision ID: 0a1b1cce6c48
Revises: 0005
Create Date: 2026-02-23 01:06:25.765547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a1b1cce6c48"
down_revision: Union[str, Sequence[str], None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "global_settings",
        "permission_mode",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "session_templates",
        "mode",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'normal'::character varying"),
    )
    op.alter_column(
        "session_templates",
        "system_prompt_mode",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'replace'::character varying"),
    )
    op.add_column("sessions", sa.Column("worktree_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "worktree_name")
    op.alter_column(
        "session_templates",
        "system_prompt_mode",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'replace'::character varying"),
    )
    op.alter_column(
        "session_templates",
        "mode",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'normal'::character varying"),
    )
    op.alter_column(
        "global_settings",
        "permission_mode",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###
