"""replace mode with workflow system

Revision ID: d606eb44b955
Revises: 0009
Create Date: 2026-02-23 07:14:09.189505

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'd606eb44b955'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_artifact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['session_artifacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_artifacts_session_id', 'session_artifacts', ['session_id'], unique=False)
    op.create_index('idx_session_artifacts_session_phase', 'session_artifacts', ['session_id', 'phase'], unique=False)
    op.create_table('artifact_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('annotation_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['session_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifact_annotations_artifact_id', 'artifact_annotations', ['artifact_id'], unique=False)
    op.add_column('global_settings', sa.Column('workflow_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('global_settings', 'mode')
    op.add_column('session_templates', sa.Column('workflow_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('session_templates', 'mode')
    op.add_column('sessions', sa.Column('workflow_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sessions', sa.Column('workflow_phase', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('workflow_phase_status', sa.String(), nullable=True))
    op.drop_column('sessions', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('mode', sa.VARCHAR(), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'workflow_phase_status')
    op.drop_column('sessions', 'workflow_phase')
    op.drop_column('sessions', 'workflow_enabled')
    op.add_column('session_templates', sa.Column('mode', sa.VARCHAR(), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('session_templates', 'workflow_enabled')
    op.add_column('global_settings', sa.Column('mode', sa.VARCHAR(), server_default=sa.text("'normal'::character varying"), autoincrement=False, nullable=True))
    op.drop_column('global_settings', 'workflow_enabled')
    op.drop_index('idx_artifact_annotations_artifact_id', table_name='artifact_annotations')
    op.drop_table('artifact_annotations')
    op.drop_index('idx_session_artifacts_session_phase', table_name='session_artifacts')
    op.drop_index('idx_session_artifacts_session_id', table_name='session_artifacts')
    op.drop_table('session_artifacts')
    # ### end Alembic commands ###
